stages:
  - deploy_production

deploy:
  image: ruby:latest
  stage: deploy
  before_script:
    -gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
  only:
    - main